process SNPEFF_ANNOTATE {
    tag "${meta.id}"
    label 'process_medium'

    conda "${moduleDir}/environment.yml"
    container "${workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container
        ? 'https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/30/30669e5208952f30d59d0d559928772f082830d01a140a853fff13a2283a17b0/data'
        : 'community.wave.seqera.io/library/snpeff:5.4.0a--eaf6ce30125b2b17'}"

    input:
    tuple val(meta), path(vcf)
    tuple val(db_meta), path(snpeff_db) // The entire snpeff_db folder from SNPEFF_BUILD
    val db_name                         // Optional name of the snpEff database, defaults to db_meta.id
    // TODO optional db-path? as value/string to make it relative to snpEff.config or absolute path?
    // TODO: add interval filter -fi , -filterInterval  <file>   : Only analyze changes that intersect with the intervals specified in this file (you may use this option many times)

    output:
    tuple val(meta), path("*.ann.vcf")    , emit: vcf
    tuple val(meta), path("*.csv")        , emit: report
    tuple val(meta), path("*.html")       , emit: summary
    tuple val(meta), path("*.genes.txt")  , emit: genes
    tuple val("${task.process}"), val('snpeff'), eval("snpEff -version 2>&1 | cut -f 2 -d '\t'"), topic: versions, emit: versions_snpeff

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: "${meta.id}"
    def avail_mem = 6144
    if (!task.memory) {
        log.info '[snpEff] Available memory not known - defaulting to 6GB.'
    } else {
        avail_mem = (task.memory.mega*0.8).intValue()
    }
    // set db_name to db_meta.id of snpeff_db folder when not supplied
    db_name = db_meta.id ? db_name : db_meta.id
    """
    # The snpeff_db folder contains:
    #   snpEff.config (generated by BUILD)
    #   data/${db_name}/ (the actual database)

    # Check if database is found
    # snpEff databases -config snpeff_db/snpEff.config| \\
    #    grep -q ${db_name} || \\
    #    echo "Database ${db_name} could not be found."; exit 1
    # NOTE: we cannot rely on the snpEff databases command because it only seems to search online
    # and defaults to looking for hg19/hg19.genome.

    # NOTE: dataDir is relative to snpEff.config when provided as a relative path
    snpEff ann \\
        -Xmx${avail_mem}M \\
        -v \\
        -config ${snpeff_db}/snpEff.config \\
        -dataDir ./data \\
        -csvStats ${prefix}.csv \\
        -stats ${prefix}.html \\
        ${args} \\
        ${db_name} \\
        ${vcf} \\
        > ${prefix}.ann.vcf
    """

    stub:
    def prefix = task.ext.prefix ?: "${meta.id}"
    """
    touch ${prefix}.ann.vcf
    touch ${prefix}.csv
    touch ${prefix}.html
    touch ${prefix}.genes.txt
    touch versions.yml
    """
}
