name: "gatk4_makesitesonlyvcf"
description: |
    Remove all sample-level genotype information from a VCF while
    retaining all site-level information.
keywords:
  - gatk4
  - vcf
tools:
  - gatk4:
      description: |
        Developed in the Data Sciences Platform at the Broad Institute, the toolkit offers a wide variety of tools
        with a primary focus on variant discovery and genotyping. Its powerful processing engine
        and high-performance computing features make it capable of taking on projects of any size.
      homepage: https://gatk.broadinstitute.org/hc/en-us
      documentation: https://gatk.broadinstitute.org/hc/en-us/categories/360002369672s
      doi: 10.1158/1538-7445.AM2017-3590
      licence: ["Apache-2.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing VCF information
          e.g. `[ id:'vcf_cohort', genome_id:'genome_1' ]`
    - vcf:
        type: file
        description: Input VCF file
        pattern: "*.{vcf,vcf.gz}"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
    - tbi:
        type: file
        description: Index file for input VCF
        pattern: "*.{tbi,csi}"
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: Genotyped VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  tbi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tbi":
          type: file
          description: Tbi index for VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_gatk4:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gatk4:
          type: string
          description: The name of the tool
      - gatk --version | sed -n '/GATK.*v/s/.*v//p':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gatk4:
          type: string
          description: The name of the tool
      - gatk --version | sed -n '/GATK.*v/s/.*v//p':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@pmoris"
