module_order:
  - fastqc:
      name: "FastQC (host removed)"
      anchor: "fastqc_decontaminated"
      info: "This section of the report shows FastQC results after host read removal."
      path_filters:
        # - "*/fastqc/hostremoved/*_fastqc.zip" # NOTE: does not work because the subdirectory hostremoved is only created in the publishdir, but the staged files in the multiqc workdir are not organised in the same manner
        - "*_hostremoved_[12]_fastqc.zip"
  - fastqc:
      name: "FastQC (trimmed)"
      anchor: "fastqc_trimmed"
      info: "This section of the report shows FastQC results after adapter trimming."
      path_filters:
        - "*_trimmed_[12]_fastqc.zip"
  - fastqc:
      name: "FastQC (raw)"
      anchor: "fastqc_raw"
      info: "This section of the report shows FastQC results of the raw reads before processing."
      path_filters:
        - "*_raw_[12]_fastqc.zip"

table_columns_visible:
  FastQC (raw):
    fastqc_raw-percent_gc: true
    fastqc_raw-percent_duplicates: false
    fastqc_raw-avg_sequence_length: false
    fastqc_raw-median_sequence_length: false
    fastqc_raw-percent_fails: false
    fastqc_raw-total_sequences: true
  FastQC (trimmed):
    fastqc_trimmed-percent_gc: false
    fastqc_trimmed-percent_duplicates: false
    fastqc_trimmed-avg_sequence_length: false
    fastqc_trimmed-median_sequence_length: true
    fastqc_trimmed-percent_fails: false
    fastqc_trimmed-total_sequences: true
  FastQC (host removed):
    fastqc_host_removed-percent_gc: true
    fastqc_host_removed-percent_duplicates: false
    fastqc_host_removed-avg_sequence_length: false
    fastqc_host_removed-median_sequence_length: false
    fastqc_host_removed-percent_fails: false
    fastqc_host_removed-total_sequences: true

table_columns_name:
  FastQC (raw):
    fastqc_raw-total_sequences: 'Reads (raw)'
    fastqc_raw-percent_gc: 'GC (raw)'
  FastQC (trimmed):
    fastqc_trimmed-total_sequences: 'Reads (trimmed)'
    fastqc_trimmed-median_sequence_length: 'Median read length (trimmed)'
  FastQC (host removed):
    fastqc_host_removed-total_sequences: 'Reads (host removed)'
    fastqc_host_removed-percent_gc: 'GC (host removed)'

picard_config:
  s_name_filenames: true

plots_force_interactive: true

report_comment: >
  This report has been generated by the <a href="https://github.com/ITMmalaria/plasmovar/releases/tag/0.3.0" target="_blank">ITMmalaria/plasmovar</a> analysis pipeline.
report_section_order:
  "ITMmalaria-plasmovar-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "ITMmalaria-plasmovar-summary":
    order: -1002

export_plots: true

disable_version_detection: true
